x = input('digite algo: ')
print('o tipo primitivo desse valor é', type(x))
print('só tem espaços?', x.isspace())
print('só tem números?', x.isnumeric())
print('é alfabetico?', x.isalpha())
print('nome e numeros?', x.isalnum())
print('está em maiuscula?', x.isupper())
print('está em minuscula?', x.islower())